---
version: "3.9"

networks:
  rtx-network: null

services:
  api:
    image: rtx/api
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: rtx.api
    networks:
      - rtx-network
    ports:
      - "5000:80" # expose port 5000 on the host and map it to port 80 in the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  client:
    image: rtx/client
    build:
      context: client/
      dockerfile: Dockerfile
    container_name: rtx.client
    depends_on:
      - api
    links:
      - api
    networks:
      - rtx-network
    ports:
      - "80:80" # expose port 80 on the host and map it to port 80 in the container
    environment:
      - VITE_API_URL=/api # set the API location to /api for the client
